---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: altibase-dbs-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/altibase/dbs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: altibase-dbs-pvc
  labels:
    app: altibase
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: altibase
  labels:
    app: altibase
spec:
  selector:
    matchLabels:
      app: altibase
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: altibase
    spec:
      containers:
      - image: altibase/altibase
        name: altibase
        ports:
        - containerPort: 20300
          name: altibase-port
        env:
        - name: MODE
          value: "daemon"
        volumeMounts:
        - name: altibase-dbs-pv
          mountPath: /home/altibase/altibase_home/dbs
      volumes:
        - name: altibase-dbs-pv
          persistentVolumeClaim:
            claimName: altibase-dbs-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: altibase-svc
spec:
 type: NodePort
 selector:
   app: altibase
 ports:
   - name: client
     protocol: TCP
     port: 20300
     nodePort: 30300
 selector:
   app: altibase
